# Generated by Django 4.1.3 on 2022-12-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_categories_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='category',
        ),
    ]
